### ISSUE TITLE
adding altmetric badge for Scientific Data page

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.org#9]
We should add an altmetric badge for the AusTraits paper to our website.

Appears that this is where to start searching for information: https://www.altmetric.com/products/altmetric-badges/

**Comment by dfalster** [comment]
Can access badge for the paper in Scientific Data from:

https://nature.altmetric.com/details/114271024

```
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script><div class="altmetric-embed" data-badge-type="donut" data-altmetric-id="114271024"></div>
```

**Comment by dfalster** [comment]
Several ways to display, what works best?

![image](https://user-images.githubusercontent.com/3589590/150928547-c9901a84-376c-4259-8135-0989fdb5b4ec.jpeg)
